class BotConstants:
    # Hunt/Battle
    HUNT_INTERVAL_MIN = 20
    HUNT_INTERVAL_MAX = 30
    BATTLE_DELAY_MIN = 3
    BATTLE_DELAY_MAX = 7
    
    # Pray
    PRAY_INTERVAL_MIN = 360
    PRAY_INTERVAL_MAX = 600
    PRAY_REQUIRED_CYCLES = 2
    
    # Exp
    EXP_INTERVAL_MIN = 17
    EXP_INTERVAL_MAX = 55
    QUOTE_THRESHOLD_MIN = 2
    QUOTE_THRESHOLD_MAX = 4
    
    # Sleep - Active/Break schedule
    SLEEP_ACTIVE_MIN = 600
    SLEEP_ACTIVE_MAX = 900
    SLEEP_BREAK_MIN = 333
    SLEEP_BREAK_MAX = 666
    
    # Command delay
    COMMAND_DELAY_MIN = 3
    COMMAND_DELAY_MAX = 7
    MIN_COMMAND_INTERVAL = 3
    
    # Gems
    GEM_CHECK_MIN = 222
    GEM_CHECK_MAX = 777
    GEM_USE_COOLDOWN = 10
    
    # Weapons
    WEAPON_INTERVAL_MIN = 66
    WEAPON_INTERVAL_MAX = 99
    WEAPON_BUY_COOLDOWN_MIN = 7
    WEAPON_BUY_COOLDOWN_MAX = 25
    WEAPON_SHARDS_THRESHOLD = 40
    WEAPON_MAX_RETRIES = 5
    
    # Sell
    SELL_INTERVAL_MIN = 1800
    SELL_INTERVAL_MAX = 3600
    
    # Rate limit
    RATE_LIMIT_SLEEP = 120
    GLOBAL_CMD_DELAY = 3
    RATE_LIMIT_RETRY_DELAY = 5
    
    # Messages
    MAX_MESSAGES_FETCH = 15
    MESSAGE_RETRY_COUNT = 10
    MESSAGE_RETRY_DELAY = 5
    
    # OwO Bot
    OWO_BOT_ID = "408785106942164992"
    
    # Version
    VERSION = "3.7.0"